name = "UncertainIntervals"
uuid = "1853b6f7-4c2b-4ead-9554-d01d2aac1500"
version = "0.1.0"
authors = ["Patrick Häcker <pat_h@web.de>"]

[workspace]
projects = ["test"]

[deps]
Infinities = "e1ba4f0e-776d-440f-acd9-e1d2e9742647"

[sources]
Infinities = {rev = "master", url = "https://github.com/JuliaMath/Infinities.jl"}
UseAll = {rev = "main", url = "https://github.com/PatrickHaecker/UseAll.jl"}

[compat]
Infinities = "0.1.12"
UseAll = "0.1"
julia = "1.10"

[extras]
UseAll = "edbe3dbe-4909-5f9e-bb65-679d27932c2a"
